"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FirestoreDatabase = exports.FirebaseDatabase = exports.FirebaseAuth = exports.initializeFirebase = void 0;
var app_1 = require("@firebase/app");
Object.defineProperty(exports, "initializeFirebase", { enumerable: true, get: function () { return app_1.initializeApp; } });
var firebaseAuth_1 = require("./firebaseAuth");
Object.defineProperty(exports, "FirebaseAuth", { enumerable: true, get: function () { return firebaseAuth_1.FirebaseAuth; } });
var firebaseDatabase_1 = require("./firebaseDatabase");
Object.defineProperty(exports, "FirebaseDatabase", { enumerable: true, get: function () { return firebaseDatabase_1.FirebaseDatabase; } });
var FirestoreDatabase_1 = require("./FirestoreDatabase");
Object.defineProperty(exports, "FirestoreDatabase", { enumerable: true, get: function () { return FirestoreDatabase_1.FirestoreDatabase; } });
